/**
 * tour-print-airline-data.ts
 *
 * 備援機場 / 航空公司名稱對照表（不依賴 DB），供 TourPrintDialog 列印用。
 * 優先使用 DB 資料（useReferenceData），DB 沒有時 fallback 到這份靜態表。
 */

export const AIRPORT_NAMES: Record<string, string> = {
  TPE: '台北桃園',
  TSA: '台北松山',
  KHH: '高雄',
  RMQ: '台中',
  HKG: '香港',
  MFM: '澳門',
  NRT: '東京成田',
  HND: '東京羽田',
  KIX: '大阪關西',
  NGO: '名古屋',
  FUK: '福岡',
  CTS: '札幌',
  OKA: '沖繩',
  ICN: '首爾仁川',
  GMP: '首爾金浦',
  PUS: '釜山',
  BKK: '曼谷',
  CNX: '清邁',
  HKT: '普吉島',
  SIN: '新加坡',
  KUL: '吉隆坡',
  PVG: '上海浦東',
  SHA: '上海虹橋',
  PEK: '北京首都',
  PKX: '北京大興',
  CAN: '廣州',
  SZX: '深圳',
  MNL: '馬尼拉',
  SGN: '胡志明市',
  HAN: '河內',
  LAX: '洛杉磯',
  SFO: '舊金山',
  JFK: '紐約乾迺迪',
  SEA: '西雅圖',
  LHR: '倫敦希斯洛',
  CDG: '巴黎戴高樂',
  FRA: '法蘭克福',
  AMS: '阿姆斯特丹',
  SYD: '雪梨',
  MEL: '墨爾本',
  AKL: '奧克蘭',
}

export const AIRLINE_NAMES: Record<string, string> = {
  CI: '中華航空',
  BR: '長榮航空',
  JX: '星宇航空',
  IT: '台灣虎航',
  B7: '立榮航空',
  AE: '華信航空',
  CX: '國泰航空',
  KA: '國泰港龍',
  HX: '香港航空',
  UO: '香港快運',
  JL: '日本航空',
  NH: '全日空',
  MM: '樂桃航空',
  BC: '天馬航空',
  KE: '大韓航空',
  OZ: '韓亞航空',
  TW: '德威航空',
  LJ: '真航空',
  '7C': '濟州航空',
  SQ: '新加坡航空',
  TR: '酷航',
  MH: '馬來西亞航空',
  AK: '亞洲航空',
  TG: '泰國航空',
  FD: '泰亞航空',
  VZ: '泰越捷',
  VN: '越南航空',
  PR: '菲律賓航空',
  CA: '中國國航',
  MU: '東方航空',
  CZ: '南方航空',
  HU: '海南航空',
  UA: '聯合航空',
  AA: '美國航空',
  DL: '達美航空',
  BA: '英國航空',
  AF: '法國航空',
  LH: '漢莎航空',
  KL: '荷蘭皇家',
  EK: '阿聯酋航空',
  QR: '卡達航空',
  EY: '阿提哈德',
  QF: '澳洲航空',
  NZ: '紐西蘭航空',
}
