/**
 * @generated by scripts/codegen-permissions.ts
 *
 * ⚠️ 不要手動編輯這個檔
 *
 * 改 module 定義請改 src/modules/<code>.ts、然後跑：
 *
 *   npm run codegen:permissions
 *
 * 紀律：modules/ 是 SOURCE、此檔是衍生產物。
 * 詳見 src/modules/README.md
 */

/**
 * Capability 常數（modules/ 衍生 + non-module exception + legacy）
 *
 * 跟 role_capabilities 表的 capability_code 欄位 1:1 對應。
 * caller 用：requireCapability(req, CAPABILITIES.HR_MANAGE_ROLES) 之類。
 */

export const CAPABILITIES = {

  // ════ module 衍生（從 src/modules/* 自動產出）════
  // ── calendar ──
  CALENDAR_READ: 'calendar.read',
  CALENDAR_MANAGE: 'calendar.write',
  // ── todos ──
  TODOS_READ: 'todos.read',
  TODOS_WRITE: 'todos.write',
  // ── channels ──
  CHANNELS_READ: 'channels.read',
  CHANNELS_WRITE: 'channels.write',
  CHANNELS_MANAGE_READ: 'channels.manage.read',
  CHANNELS_MANAGE_WRITE: 'channels.manage.write',
  CHANNELS_ANNOUNCEMENT_READ: 'channels.announcement.read',
  CHANNELS_ANNOUNCEMENT_WRITE: 'channels.announcement.write',
  // ── tours ──
  TOURS_READ: 'tours.read',
  TOURS_WRITE: 'tours.write',
  TOURS_OVERVIEW_READ: 'tours.overview.read',
  TOURS_OVERVIEW_WRITE: 'tours.overview.write',
  TOURS_ORDERS_READ: 'tours.orders.read',
  TOURS_ORDERS_WRITE: 'tours.orders.write',
  TOURS_MEMBERS_READ: 'tours.members.read',
  TOURS_MEMBERS_WRITE: 'tours.members.write',
  TOURS_ITINERARY_READ: 'tours.itinerary.read',
  TOURS_ITINERARY_WRITE: 'tours.itinerary.write',
  TOURS_DISPLAY_ITINERARY_READ: 'tours.display-itinerary.read',
  TOURS_DISPLAY_ITINERARY_WRITE: 'tours.display-itinerary.write',
  TOURS_QUOTE_READ: 'tours.quote.read',
  TOURS_QUOTE_WRITE: 'tours.quote.write',
  TOURS_CONTRACT_READ: 'tours.contract.read',
  TOURS_CONTRACT_WRITE: 'tours.contract.write',
  TOURS_CLOSING_READ: 'tours.closing.read',
  TOURS_CLOSING_WRITE: 'tours.closing.write',
  // ── orders ──
  ORDERS_READ: 'orders.read',
  ORDERS_WRITE: 'orders.write',
  ORDERS_LIST_READ: 'orders.list.read',
  ORDERS_LIST_WRITE: 'orders.list.write',
  ORDERS_CREATE_READ: 'orders.create.read',
  ORDERS_CREATE_WRITE: 'orders.create.write',
  ORDERS_EDIT_READ: 'orders.edit.read',
  ORDERS_EDIT_WRITE: 'orders.edit.write',
  ORDERS_PAYMENTS_READ: 'orders.payments.read',
  ORDERS_PAYMENTS_WRITE: 'orders.payments.write',
  ORDERS_TRAVELERS_READ: 'orders.travelers.read',
  ORDERS_TRAVELERS_WRITE: 'orders.travelers.write',
  // ── finance ──
  FINANCE_READ_PAYMENTS: 'finance.payments.read',
  FINANCE_MANAGE_PAYMENTS: 'finance.payments.write',
  FINANCE_READ_PAYMENTS_COMPANY: 'finance.payments-company.read',
  FINANCE_PAYMENTS_COMPANY_WRITE: 'finance.payments-company.write',
  FINANCE_PAYMENTS_CONFIRM_READ: 'finance.payments-confirm.read',
  FINANCE_CONFIRM_PAYMENTS: 'finance.payments-confirm.write',
  FINANCE_READ_REQUESTS: 'finance.requests.read',
  FINANCE_MANAGE_REQUESTS: 'finance.requests.write',
  FINANCE_READ_REQUESTS_COMPANY: 'finance.requests-company.read',
  FINANCE_REQUESTS_COMPANY_WRITE: 'finance.requests-company.write',
  FINANCE_READ_REQUESTS_SALARY: 'finance.requests-salary.read',
  FINANCE_REQUESTS_SALARY_WRITE: 'finance.requests-salary.write',
  FINANCE_READ_TREASURY: 'finance.treasury.read',
  FINANCE_TREASURY_WRITE: 'finance.treasury.write',
  FINANCE_READ_DISBURSEMENT: 'finance.disbursement.read',
  FINANCE_MANAGE_DISBURSEMENT: 'finance.disbursement.write',
  FINANCE_READ_REPORTS: 'finance.reports.read',
  FINANCE_REPORTS_WRITE: 'finance.reports.write',
  FINANCE_READ_SETTINGS: 'finance.settings.read',
  FINANCE_MANAGE_SETTINGS: 'finance.settings.write',
  // ── accounting ──
  ACCOUNTING_VOUCHERS_READ: 'accounting.vouchers.read',
  ACCOUNTING_VOUCHERS_WRITE: 'accounting.vouchers.write',
  ACCOUNTING_ACCOUNTS_READ: 'accounting.accounts.read',
  ACCOUNTING_ACCOUNTS_WRITE: 'accounting.accounts.write',
  ACCOUNTING_PERIOD_CLOSING_READ: 'accounting.period-closing.read',
  ACCOUNTING_PERIOD_CLOSING_WRITE: 'accounting.period-closing.write',
  ACCOUNTING_OPENING_BALANCES_READ: 'accounting.opening-balances.read',
  ACCOUNTING_OPENING_BALANCES_WRITE: 'accounting.opening-balances.write',
  ACCOUNTING_CHECKS_READ: 'accounting.checks.read',
  ACCOUNTING_CHECKS_WRITE: 'accounting.checks.write',
  ACCOUNTING_REPORTS_READ: 'accounting.reports.read',
  ACCOUNTING_REPORTS_WRITE: 'accounting.reports.write',
  // ── office ──
  OFFICE_READ: 'office.read',
  OFFICE_WRITE: 'office.write',
  // ── hr ──
  HR_READ_EMPLOYEES: 'hr.employees.read',
  HR_MANAGE_EMPLOYEES: 'hr.employees.write',
  HR_READ_ROLES: 'hr.roles.read',
  HR_MANAGE_ROLES: 'hr.roles.write',
  // ── database ──
  DATABASE_CUSTOMERS_READ: 'database.customers.read',
  DATABASE_CUSTOMERS_WRITE: 'database.customers.write',
  DATABASE_READ_ATTRACTIONS: 'database.attractions.read',
  DATABASE_MANAGE_ATTRACTIONS: 'database.attractions.write',
  DATABASE_SUPPLIERS_READ: 'database.suppliers.read',
  DATABASE_SUPPLIERS_WRITE: 'database.suppliers.write',
  DATABASE_ARCHIVE_READ: 'database.archive.read',
  DATABASE_ARCHIVE_WRITE: 'database.archive.write',
  // ── ai_hub ──
  AI_HUB_READ: 'ai_hub.read',
  AI_HUB_WRITE: 'ai_hub.write',
  // ── settings ──
  SETTINGS_PERSONAL_READ: 'settings.personal.read',
  SETTINGS_MANAGE_PERSONAL: 'settings.personal.write',
  SETTINGS_READ_COMPANY: 'settings.company.read',
  SETTINGS_MANAGE_COMPANY: 'settings.company.write',
  // ── dashboard ──
  DASHBOARD_READ: 'dashboard.read',
  DASHBOARD_WRITE: 'dashboard.write',
  // ── customers ──
  CUSTOMERS_READ: 'customers.read',
  CUSTOMERS_WRITE: 'customers.write',
  // ── tour_attributes ──
  TOUR_ATTRIBUTES_READ: 'tour_attributes.read',
  TOUR_ATTRIBUTES_WRITE: 'tour_attributes.write',
  // ── workspaces ──
  WORKSPACES_READ: 'workspaces.read',
  WORKSPACES_WRITE: 'workspaces.write',
  // ── shared_data_management ──
  SHARED_DATA_MANAGEMENT_READ: 'shared_data_management.read',
  SHARED_DATA_MANAGEMENT_WRITE: 'shared_data_management.write',
  // ── platform_integrations ──
  PLATFORM_INTEGRATIONS_READ: 'platform_integrations.read',
  PLATFORM_INTEGRATIONS_WRITE: 'platform_integrations.write',
  // ── addon_data_attractions ──
  ADDON_DATA_ATTRACTIONS_READ: 'addon_data_attractions.read',
  ADDON_DATA_ATTRACTIONS_WRITE: 'addon_data_attractions.write',
  // ── addon_data_hotels ──
  ADDON_DATA_HOTELS_READ: 'addon_data_hotels.read',
  ADDON_DATA_HOTELS_WRITE: 'addon_data_hotels.write',
  // ── addon_data_restaurants ──
  ADDON_DATA_RESTAURANTS_READ: 'addon_data_restaurants.read',
  ADDON_DATA_RESTAURANTS_WRITE: 'addon_data_restaurants.write',
  // ── hr_salary_settlement ──
  HR_SALARY_SETTLEMENT_READ: 'hr_salary_settlement.read',
  HR_SALARY_SETTLEMENT_WRITE: 'hr_salary_settlement.write',
  // ── hr_bonus_settlement ──
  HR_BONUS_SETTLEMENT_READ: 'hr_bonus_settlement.read',
  HR_BONUS_SETTLEMENT_WRITE: 'hr_bonus_settlement.write',
  // ── documents ──
  DOCUMENTS_FILES_READ: 'documents.files.read',
  DOCUMENTS_FILES_WRITE: 'documents.files.write',
  DOCUMENTS_SEALS_READ: 'documents.seals.read',
  DOCUMENTS_SEALS_WRITE: 'documents.seals.write',
  // ── esim ──
  ESIM_ORDERS_READ: 'esim.orders.read',
  ESIM_ORDERS_WRITE: 'esim.orders.write',
  ESIM_PRODUCTS_READ: 'esim.products.read',
  ESIM_PRODUCTS_WRITE: 'esim.products.write',
  ESIM_SETTINGS_READ: 'esim.settings.read',
  ESIM_SETTINGS_WRITE: 'esim.settings.write',
  // ── visas ──
  VISAS_APPLICATIONS_READ: 'visas.applications.read',
  VISAS_APPLICATIONS_WRITE: 'visas.applications.write',
  VISAS_DOCUMENTS_READ: 'visas.documents.read',
  VISAS_DOCUMENTS_WRITE: 'visas.documents.write',
  VISAS_DOCUMENT_TYPES_READ: 'visas.document_types.read',
  VISAS_DOCUMENT_TYPES_WRITE: 'visas.document_types.write',
  VISAS_SERVICE_TYPES_READ: 'visas.service_types.read',
  VISAS_SERVICE_TYPES_WRITE: 'visas.service_types.write',
  VISAS_PRICING_READ: 'visas.pricing.read',
  VISAS_PRICING_WRITE: 'visas.pricing.write',
  // ── marketing ──
  MARKETING_WEBSITE_READ: 'marketing.website.read',
  MARKETING_WEBSITE_WRITE: 'marketing.website.write',

  // ════ Non-module（scope / 全域 capability、不屬任何 module）════
  CROSS_BRANCH_READ: 'cross_branch.read',
  CROSS_BRANCH_WRITE: 'cross_branch.write',

  // ════ Legacy（現有 caller 還在用、modules/ 沒衍生對應、之後審視）════
  CHANNELS_MANAGE: 'channels.manage',
  FINANCE_ADVANCE_PAYMENT_WRITE: 'finance.advance_payment.write',
  LINE_BOT_CONFIG: 'line_bot.config',
  LINE_BOT_READ: 'line_bot.read',
  LINE_BOT_WRITE: 'line_bot.write',
  MANAGE_ENV_SETTINGS: 'settings.env.write',
} as const

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES]
