/**
 * @generated by scripts/codegen-permissions.ts
 *
 * ⚠️ 不要手動編輯這個檔
 *
 * 改 module 定義請改 src/modules/<code>.ts、然後跑：
 *
 *   npm run codegen:permissions
 *
 * 紀律：modules/ 是 SOURCE、此檔是衍生產物。
 * 詳見 src/modules/README.md
 */

/**
 * 功能模組定義
 *
 * 用於租戶功能權限管理、對應側邊欄路由
 */

export interface FeatureDefinition {
  code: string
  name: string
  description: string
  category: 'basic' | 'premium' | 'enterprise' | 'addon'
  routes: string[]
}

// 所有功能模組（從 src/modules/* 衍生）
export const FEATURES: FeatureDefinition[] = [
  {
    code: 'calendar',
    name: '行事曆',
    description: '出團日曆',
    category: 'basic',
    routes: [
      '/calendar',
    ],
  },
  {
    code: 'todos',
    name: '待辦事項',
    description: '任務管理',
    category: 'basic',
    routes: [
      '/todos',
    ],
  },
  {
    code: 'channels',
    name: '溝通頻道',
    description: '內部訊息、公告、專案頻道、HAPPY AI DM',
    category: 'basic',
    routes: [
      '/channels',
      '/channels/[id]',
    ],
  },
  {
    code: 'channels.happy',
    name: 'HAPPY 機器人',
    description: 'AI 助手「哈比」進駐頻道、能查訂單 / 客戶 / 旅遊團資料',
    category: 'premium',
    routes: [
      '/channels',
      '/channels/[id]',
    ],
  },
  {
    code: 'tours',
    name: '旅遊團管理',
    description: '團務管理核心功能',
    category: 'basic',
    routes: [
      '/tours',
      '/tours/[code]',
    ],
  },
  {
    code: 'orders',
    name: '訂單管理',
    description: '客戶訂單與報名',
    category: 'basic',
    routes: [
      '/orders',
    ],
  },
  {
    code: 'finance',
    name: '財務系統',
    description: '收款、請款、出納',
    category: 'basic',
    routes: [
      '/finance',
      '/finance/payments',
      '/finance/requests',
      '/finance/treasury',
      '/finance/treasury/disbursement',
      '/finance/reports',
      '/finance/settings',
    ],
  },
  {
    code: 'accounting',
    name: '會計系統',
    description: '傳票、帳務、結算',
    category: 'premium',
    routes: [
      '/accounting',
      '/accounting/vouchers',
      '/accounting/accounts',
      '/accounting/reports',
      '/accounting/checks',
      '/accounting/period-closing',
    ],
  },
  {
    code: 'office',
    name: '文件管理',
    description: '文件編輯與儲存',
    category: 'basic',
    routes: [],
  },
  {
    code: 'hr',
    name: '人資管理',
    description: '員工 + 職務管理',
    category: 'basic',
    routes: [
      '/hr',
      '/hr/roles',
      '/hr/organization',
    ],
  },
  {
    code: 'database',
    name: '資料管理',
    description: '客戶、供應商、資源',
    category: 'basic',
    routes: [
      '/library',
      '/library/attractions',
      '/library/suppliers',
      '/library/archive-management',
    ],
  },
  {
    code: 'ai_hub',
    name: 'AI Hub',
    description: 'AI 整合平台 — 多通路對話統一收件匣 + AI 助理 + 對話分析',
    category: 'premium',
    routes: [
      '/ai',
    ],
  },
  {
    code: 'settings',
    name: '系統設定',
    description: '公司與系統配置',
    category: 'basic',
    routes: [
      '/settings',
      '/settings/company',
      '/settings/personal',
    ],
  },
  {
    code: 'dashboard',
    name: '首頁',
    description: '系統首頁與儀表板',
    category: 'basic',
    routes: [
      '/dashboard',
    ],
  },
  {
    code: 'customers',
    name: '顧客管理',
    description: '客戶資料',
    category: 'premium',
    routes: [
      '/library/customers',
    ],
  },
  {
    code: 'tour_attributes',
    name: '旅行屬性功能',
    description: '選擇團類型：機票、機加酒、訂房、派車、旅遊團',
    category: 'premium',
    routes: [
      '/tours',
    ],
  },
  {
    code: 'workspaces',
    name: '租戶管理',
    description: '管理所有 workspace（建立 / 編輯 / 停用其他公司租戶）— 跨 workspace 能力、限漫途使用',
    category: 'enterprise',
    routes: [
      '/workspaces',
    ],
  },
  {
    code: 'shared_data_management',
    name: '共用資料管理',
    description: '維護全平台共用資料（金融機構代號、機場代號等 ref_* 表）— 跨 workspace 能力、限漫途使用、UI 入口未開放',
    category: 'enterprise',
    routes: [],
  },
  {
    code: 'platform_integrations',
    name: '平台整合',
    description: '第三方 SaaS 整合（AiToEarn 內容自動分發等）— iframe / API 接入、workspace 內功能',
    category: 'enterprise',
    routes: [
      '/platform',
      '/platform/aitoearn',
    ],
  },
  {
    code: 'addon_data_attractions',
    name: '景點資料庫',
    description: '購買後可讀漫途整理的景點公共池資料',
    category: 'addon',
    routes: [],
  },
  {
    code: 'addon_data_hotels',
    name: '飯店資料庫',
    description: '購買後可讀漫途整理的飯店公共池資料',
    category: 'addon',
    routes: [],
  },
  {
    code: 'addon_data_restaurants',
    name: '餐廳資料庫',
    description: '購買後可讀漫途整理的餐廳公共池資料',
    category: 'addon',
    routes: [],
  },
  {
    code: 'hr_salary_settlement',
    name: '薪資結算',
    description: 'HR 月度薪資批次結算、產出請款單',
    category: 'basic',
    routes: [
      '/hr/salary-settlement',
      '/hr/salary-settlement/[id]',
    ],
  },
  {
    code: 'hr_bonus_settlement',
    name: '獎金結算',
    description: 'HR 按團勾選結算獎金、產出請款單',
    category: 'basic',
    routes: [
      '/hr/bonus-settlement',
      '/hr/bonus-settlement/[tourId]',
    ],
  },
  {
    code: 'documents',
    name: '文件中心',
    description: '上傳、編輯、蓋章、合併文件（PDF / Word / Excel / PPT）',
    category: 'basic',
    routes: [
      '/documents',
      '/documents/[id]',
    ],
  },
  {
    code: 'travel_invoice',
    name: '電子收據',
    description: '台灣電子發票開立、作廢、折讓、查詢與重寄',
    category: 'premium',
    routes: [
      '/travel-invoice',
      '/travel-invoice/issue',
      '/travel-invoice/void',
      '/travel-invoice/allowance',
      '/travel-invoice/query',
      '/travel-invoice/resend',
      '/travel-invoice/settings',
    ],
  },
  {
    code: 'esim',
    name: 'eSIM 管理',
    description: '旅遊 eSIM 訂單管理（Worldmove）、產品目錄與 API 設定',
    category: 'basic',
    routes: [
      '/esim',
      '/esim/orders',
      '/esim/products',
      '/esim/settings',
    ],
  },
  {
    code: 'visas',
    name: '簽證代辦',
    description: '證件代辦進度管理、客戶證件抽屜、代辦商價目（含版本歷史）',
    category: 'basic',
    routes: [
      '/visas',
      '/library/document-types',
      '/library/application-service-types',
      '/suppliers/[code]/pricing',
    ],
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Helper functions（保留現有 API、caller 不需動）

export function getFeatureByCode(code: string): FeatureDefinition | undefined {
  return FEATURES.find((f) => f.code === code)
}

export function getFeatureByRoute(route: string): FeatureDefinition | undefined {
  const normalizedRoute = route.replace(/\/\[.*?\]/g, '/[param]')
  return FEATURES.find((f) =>
    f.routes.some((r) => {
      const normalizedFeatureRoute = r.replace(/\/\[.*?\]/g, '/[param]')
      return (
        route.startsWith(normalizedFeatureRoute.replace('/[param]', '')) ||
        normalizedRoute === normalizedFeatureRoute
      )
    }),
  )
}

export function getFeaturesByRoute(route: string): FeatureDefinition[] {
  const normalizedRoute = route.replace(/\/\[.*?\]/g, '/[param]')
  return FEATURES.filter((f) =>
    f.routes.some((r) => {
      const normalizedFeatureRoute = r.replace(/\/\[.*?\]/g, '/[param]')
      return (
        route.startsWith(normalizedFeatureRoute.replace('/[param]', '')) ||
        normalizedRoute === normalizedFeatureRoute
      )
    }),
  )
}

export function getBasicFeatures(): FeatureDefinition[] {
  return FEATURES.filter((f) => f.category === 'basic')
}

export function getPremiumFeatures(): FeatureDefinition[] {
  return FEATURES.filter((f) => f.category === 'premium')
}

export function getEnterpriseFeatures(): FeatureDefinition[] {
  return FEATURES.filter((f) => f.category === 'enterprise')
}

export function getAddonFeatures(): FeatureDefinition[] {
  return FEATURES.filter((f) => f.category === 'addon')
}
