/**
 * @generated by scripts/codegen-permissions.ts
 *
 * ⚠️ 不要手動編輯這個檔
 *
 * 改 module 定義請改 src/modules/<code>.ts、然後跑：
 *
 *   npm run codegen:permissions
 *
 * 紀律：modules/ 是 SOURCE、此檔是衍生產物。
 * 詳見 src/modules/README.md
 */

/**
 * 模組分頁權限定義（HR /hr/roles UI 用）
 *
 * 從 src/modules/* 衍生、只 export exposedToHr !== false 的 module
 */

export interface ModuleTab {
  code: string
  name: string
  description?: string
  /**
   * tab 層級功能分類（workspace 層級開關用）
   */
  category?: 'basic' | 'premium'
}

export interface ModuleDefinition {
  code: string
  name: string
  description?: string
  tabs: ModuleTab[]
}

// 模組與分頁定義（順序：src/modules/_registry.ts ALL_MODULES）
export const MODULES: ModuleDefinition[] = [
  {
    code: 'channels',
    name: '溝通頻道',
    description: '內部訊息、公告、專案頻道、HAPPY AI DM',
    tabs: [
      {
        code: 'manage',
        name: '管理頻道',
        description: '建 / 刪 / 改頻道設定（限管理員）',
      },
      {
        code: 'announcement',
        name: '發送公告',
        description: '在公告類頻道（重要事項 / 日常公告 / 表揚紀錄）發送訊息',
      },
    ],
  },
  {
    code: 'tours',
    name: '旅遊團管理',
    description: '團務管理核心功能',
    tabs: [
      {
        code: 'overview',
        name: '總覽',
        description: '團號、日期、目的地、負責人',
      },
      {
        code: 'orders',
        name: '訂單',
        description: '報名訂單、付款狀態',
      },
      {
        code: 'members',
        name: '團員',
        description: '團員資料、護照、聯絡資訊',
      },
      {
        code: 'itinerary',
        name: '行程',
        description: '每日行程內容',
      },
      {
        code: 'display-itinerary',
        name: '展示行程',
        description: '對客展示用行程頁面編輯器',
        category: 'premium',
      },
      {
        code: 'quote',
        name: '報價',
        description: '報價計算、成本',
      },
      {
        code: 'contract',
        name: '合約',
        description: '旅遊合約、電子簽約',
        category: 'premium',
      },
      {
        code: 'closing',
        name: '結案',
        description: '結案報表、損益確認',
      },
      {
        code: 'template',
        name: '可建立模板',
        description: '能把行程存成標準模板供重複使用（建正式團/提案不需此能力）',
      },
    ],
  },
  {
    code: 'orders',
    name: '訂單管理',
    description: '客戶訂單與報名',
    tabs: [
      {
        code: 'list',
        name: '訂單列表',
        description: '所有訂單總覽',
      },
      {
        code: 'create',
        name: '新增訂單',
        description: '建立新訂單',
      },
      {
        code: 'edit',
        name: '編輯訂單',
        description: '修改訂單內容',
      },
      {
        code: 'payments',
        name: '付款記錄',
        description: '訂單收款狀態',
      },
      {
        code: 'travelers',
        name: '旅客資料',
        description: '旅客護照、聯絡資訊',
      },
    ],
  },
  {
    code: 'finance',
    name: '財務系統',
    description: '收款、請款、出納',
    tabs: [
      {
        code: 'payments',
        name: '收款管理',
        description: '客戶收款記錄',
      },
      {
        code: 'payments-company',
        name: '公司收款',
        description: '非團體的公司收款',
      },
      {
        code: 'payments-confirm',
        name: '確認核帳',
        description: '收款確認與核帳',
      },
      {
        code: 'requests',
        name: '請款管理',
        description: '團體請款',
      },
      {
        code: 'requests-company',
        name: '公司請款',
        description: '非團體的公司支出',
      },
      {
        code: 'requests-salary',
        name: '薪資請款',
        description: '員工薪資請款（與公司請款權限隔離）',
      },
      {
        code: 'disbursement',
        name: '出納管理',
        description: '撥款作業',
      },
      {
        code: 'reports',
        name: '報表管理',
        description: '財務報表',
      },
      {
        code: 'settings',
        name: '財務設定',
        description: '付款方式、科目設定',
      },
      {
        code: 'advance_payment',
        name: '可代墊款',
        description: '有此能力的人出現在請款頁「代墊款人」下拉',
      },
    ],
  },
  {
    code: 'accounting',
    name: '會計系統',
    description: '傳票、帳務、結算',
    tabs: [
      {
        code: 'vouchers',
        name: '傳票管理',
        description: '記帳傳票',
      },
      {
        code: 'accounts',
        name: '科目管理',
        description: '會計科目設定',
      },
      {
        code: 'period-closing',
        name: '期末結轉',
        description: '月結、年結',
      },
      {
        code: 'opening-balances',
        name: '期初餘額',
        description: '期初設定',
      },
      {
        code: 'checks',
        name: '票據管理',
        description: '支票、本票',
      },
      {
        code: 'reports',
        name: '會計報表',
        description: '損益表、資產負債表',
      },
    ],
  },
  {
    code: 'hr',
    name: '人資管理',
    description: '員工 + 職務管理',
    tabs: [
      {
        code: 'employees',
        name: '員工管理',
        description: '員工資料、到職離職',
      },
      {
        code: 'roles',
        name: '職務管理',
        description: '職務角色與權限',
      },
    ],
  },
  {
    code: 'database',
    name: '資料管理',
    description: '客戶、供應商、資源',
    tabs: [
      {
        code: 'customers',
        name: '顧客管理',
        description: '個人客戶',
      },
      {
        code: 'attractions',
        name: '旅遊資料庫',
        description: '景點、餐廳、飯店',
      },
      {
        code: 'suppliers',
        name: '供應商管理',
        description: '合作供應商',
      },
      {
        code: 'archive',
        name: '封存管理',
        description: '封存資料查閱',
      },
    ],
  },
  {
    code: 'ai_hub',
    name: 'AI Hub',
    description: 'AI 整合平台 — 多通路對話統一收件匣 + AI 助理 + 對話分析',
    tabs: [],
  },
  {
    code: 'settings',
    name: '系統設定',
    description: '公司與系統配置',
    tabs: [
      {
        code: 'company',
        name: '公司設定',
        description: '公司名稱、Logo、聯絡方式、環境變數',
      },
    ],
  },
  {
    code: 'tour_attributes',
    name: '旅行屬性功能',
    description: '選擇團類型：機票、機加酒、訂房、派車、旅遊團',
    tabs: [],
  },
  {
    code: 'workspaces',
    name: '租戶管理',
    description:
      '管理所有 workspace（建立 / 編輯 / 停用其他公司租戶）— 跨 workspace 能力、限漫途使用',
    tabs: [],
  },
  {
    code: 'shared_data_management',
    name: '共用資料管理',
    description:
      '維護全平台共用資料（金融機構代號、機場代號等 ref_* 表）— 跨 workspace 能力、限漫途使用、UI 入口未開放',
    tabs: [],
  },
  {
    code: 'hr_salary_settlement',
    name: '薪資結算',
    description: 'HR 月度薪資批次結算、產出請款單',
    tabs: [],
  },
  {
    code: 'hr_bonus_settlement',
    name: '獎金結算',
    description: 'HR 按團勾選結算獎金、產出請款單',
    tabs: [],
  },
  {
    code: 'documents',
    name: '文件中心',
    description: '上傳、編輯、蓋章、合併文件（PDF / Word / Excel / PPT）',
    tabs: [
      {
        code: 'files',
        name: '我的文件',
        description: '上傳、管理、下載文件',
      },
      {
        code: 'seals',
        name: '章印管理',
        description: '管理公司章印圖片',
      },
    ],
  },
  {
    code: 'esim',
    name: 'eSIM 管理',
    description: '旅遊 eSIM 訂單管理（Worldmove）、產品目錄與 API 設定',
    tabs: [
      {
        code: 'orders',
        name: '訂單管理',
        description: '客戶 eSIM 訂單查詢與管理',
      },
      {
        code: 'products',
        name: '產品目錄',
        description: 'Worldmove eSIM 產品列表',
      },
      {
        code: 'settings',
        name: 'eSIM 設定',
        description: 'Worldmove API 串接設定',
      },
    ],
  },
  {
    code: 'visas',
    name: '簽證代辦',
    description: '證件代辦進度管理、客戶證件抽屜、代辦商價目（含版本歷史）',
    tabs: [
      {
        code: 'applications',
        name: '申辦進度',
        description: '送件、取件、退件、歸還客戶',
      },
      {
        code: 'documents',
        name: '客戶證件抽屜',
        description: '客戶所持證件總覽、含申辦歷史',
      },
      {
        code: 'document_types',
        name: '證件種類',
        description: '證件分類字典維護（護照、台胞證、各國簽證等）',
      },
      {
        code: 'service_types',
        name: '服務種類',
        description: '代辦服務種類字典（含一般 / 急件區分）',
      },
      {
        code: 'pricing',
        name: '代辦商價目',
        description: '各代辦商對各服務的價目（含版本歷史）',
      },
    ],
  },
  {
    code: 'marketing',
    name: '行銷管理',
    description: '官網行程上架、行銷文案、SEO 設定（Corner 官網等）',
    tabs: [
      {
        code: 'website',
        name: '官網管理',
        description: '管理哪些團上架到 Corner 官網、編輯行銷文案 / SEO / 封面圖、觸發 rebuild',
      },
    ],
  },
  {
    code: 'websites',
    name: '客戶官網系統',
    description: '加購後可進 design 編輯器自由排版、發布到 {subdomain}.venturo.tw',
    tabs: [
      {
        code: 'design',
        name: '版面設計',
        description: '進全螢幕編輯器、從 component 變體庫拼版面、改文案 / 配色 / 發布',
      },
      {
        code: 'products',
        name: '產品上架',
        description: '挑哪些團要上架到客戶官網、編輯行銷文案 / SEO / 封面圖',
      },
    ],
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Helper functions（保留現有 API）

export function getModuleByCode(code: string): ModuleDefinition | undefined {
  return MODULES.find(m => m.code === code)
}

export function getModulesWithTabs(): ModuleDefinition[] {
  return MODULES.filter(m => m.tabs.length > 0)
}

export function getModulesWithoutTabs(): ModuleDefinition[] {
  return MODULES.filter(m => m.tabs.length === 0)
}

export function getAllModulesSorted(): ModuleDefinition[] {
  return [...getModulesWithTabs(), ...getModulesWithoutTabs()]
}
