import { EDITOR_MEDIA_LABELS } from './media'
import { EDITOR_ITINERARY_LABELS } from './itinerary'
import { EDITOR_UI_LABELS } from './ui'

export { EDITOR_MEDIA_LABELS, EDITOR_ITINERARY_LABELS, EDITOR_UI_LABELS }

export const COMP_EDITOR_LABELS = {
  ...EDITOR_MEDIA_LABELS,
  ...EDITOR_ITINERARY_LABELS,
  ...EDITOR_UI_LABELS,
}
