#!/usr/bin/env tsx
/**
 * codegen-permissions.ts — 從 src/modules/* 衍生 features.ts + module-tabs.ts
 *
 * 跑：npm run codegen:permissions
 *
 * 哲學：modules/ 是 SOURCE、3 個 SSOT 檔是 @generated 衍生產物。
 * 改 module 定義 → 跑這個 script → 3 個檔自動同步、不會 drift。
 *
 * 本次只 overwrite features.ts + module-tabs.ts（純 data、caller 用 array、影響小）。
 * capabilities.ts 留 Phase 2B（caller 用 KEY 命名、改動風險大）。
 */

import { writeFileSync, readFileSync } from 'node:fs'
import { dirname, resolve, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { ALL_MODULES, getHrExposedModules } from '../src/modules/_registry'
import { deriveCapabilityCodes, deriveModuleTabsEntry } from '../src/modules/_define'

const __dirname = dirname(fileURLToPath(import.meta.url))
const REPO_ROOT = resolve(__dirname, '..')

const GENERATED_HEADER = `/**
 * @generated by scripts/codegen-permissions.ts
 *
 * ⚠️ 不要手動編輯這個檔
 *
 * 改 module 定義請改 src/modules/<code>.ts、然後跑：
 *
 *   npm run codegen:permissions
 *
 * 紀律：modules/ 是 SOURCE、此檔是衍生產物。
 * 詳見 src/modules/README.md
 */`

/**
 * 把 JS object 序列化成 TS 程式碼（保留型別、不用 quotes wrap key）
 */
function tsStringify(value: unknown, indent = 2, depth = 0): string {
  const pad = ' '.repeat(indent * depth)
  const padInner = ' '.repeat(indent * (depth + 1))

  if (value === null || value === undefined) return 'undefined'
  if (typeof value === 'string') return `'${value.replace(/'/g, "\\'")}'`
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]'
    const items = value.map((v) => padInner + tsStringify(v, indent, depth + 1))
    return `[\n${items.join(',\n')},\n${pad}]`
  }

  if (typeof value === 'object') {
    const entries = Object.entries(value).filter(([, v]) => v !== undefined)
    if (entries.length === 0) return '{}'
    const lines = entries.map(([k, v]) => `${padInner}${k}: ${tsStringify(v, indent, depth + 1)}`)
    return `{\n${lines.join(',\n')},\n${pad}}`
  }

  return 'null'
}

// ─────────────────────────────────────────────────────────────────────────────
// features.ts

function genFeaturesTs(): string {
  const features = ALL_MODULES.flatMap((m) => [
    {
      code: m.code,
      name: m.name,
      description: m.description ?? '',
      category: m.category,
      routes: [...m.routes],
    },
    // sub-features 衍生：module 內部子功能 feature gate（如 channels.happy）
    ...(m.subFeatures ?? []).map((sf) => ({
      code: sf.code,
      name: sf.name,
      description: sf.description ?? '',
      category: sf.category,
      routes: [...m.routes], // sub-feature 沿用 module routes
    })),
  ])

  return `${GENERATED_HEADER}

/**
 * 功能模組定義
 *
 * 用於租戶功能權限管理、對應側邊欄路由
 */

export interface FeatureDefinition {
  code: string
  name: string
  description: string
  category: 'basic' | 'premium' | 'enterprise' | 'addon'
  routes: string[]
}

// 所有功能模組（從 src/modules/* 衍生）
export const FEATURES: FeatureDefinition[] = ${tsStringify(features)}

// ─────────────────────────────────────────────────────────────────────────────
// Helper functions（保留現有 API、caller 不需動）

export function getFeatureByCode(code: string): FeatureDefinition | undefined {
  return FEATURES.find((f) => f.code === code)
}

export function getFeatureByRoute(route: string): FeatureDefinition | undefined {
  const normalizedRoute = route.replace(/\\/\\[.*?\\]/g, '/[param]')
  return FEATURES.find((f) =>
    f.routes.some((r) => {
      const normalizedFeatureRoute = r.replace(/\\/\\[.*?\\]/g, '/[param]')
      return (
        route.startsWith(normalizedFeatureRoute.replace('/[param]', '')) ||
        normalizedRoute === normalizedFeatureRoute
      )
    }),
  )
}

export function getFeaturesByRoute(route: string): FeatureDefinition[] {
  const normalizedRoute = route.replace(/\\/\\[.*?\\]/g, '/[param]')
  return FEATURES.filter((f) =>
    f.routes.some((r) => {
      const normalizedFeatureRoute = r.replace(/\\/\\[.*?\\]/g, '/[param]')
      return (
        route.startsWith(normalizedFeatureRoute.replace('/[param]', '')) ||
        normalizedRoute === normalizedFeatureRoute
      )
    }),
  )
}

export function getBasicFeatures(): FeatureDefinition[] {
  return FEATURES.filter((f) => f.category === 'basic')
}

export function getPremiumFeatures(): FeatureDefinition[] {
  return FEATURES.filter((f) => f.category === 'premium')
}

export function getEnterpriseFeatures(): FeatureDefinition[] {
  return FEATURES.filter((f) => f.category === 'enterprise')
}

export function getAddonFeatures(): FeatureDefinition[] {
  return FEATURES.filter((f) => f.category === 'addon')
}
`
}

// ─────────────────────────────────────────────────────────────────────────────
// module-tabs.ts

function genModuleTabsTs(): string {
  // 用 deriveModuleTabsEntry helper（過濾 hiddenInHr + isEligibility tab、5/13 紀律）
  const exposed = getHrExposedModules()
  const modules = exposed.map((m) => deriveModuleTabsEntry(m))

  return `${GENERATED_HEADER}

/**
 * 模組分頁權限定義（HR /hr/roles UI 用）
 *
 * 從 src/modules/* 衍生、只 export exposedToHr !== false 的 module
 */

export interface ModuleTab {
  code: string
  name: string
  description?: string
  /**
   * 是否為「下拉資格」tab（admin 可個別取消的開關）
   */
  isEligibility?: boolean
  /**
   * tab 層級功能分類（workspace 層級開關用）
   */
  category?: 'basic' | 'premium'
}

export interface ModuleDefinition {
  code: string
  name: string
  description?: string
  tabs: ModuleTab[]
}

// 模組與分頁定義（順序：src/modules/_registry.ts ALL_MODULES）
export const MODULES: ModuleDefinition[] = ${tsStringify(modules)}

// ─────────────────────────────────────────────────────────────────────────────
// Helper functions（保留現有 API）

export function getModuleByCode(code: string): ModuleDefinition | undefined {
  return MODULES.find((m) => m.code === code)
}

export function getModulesWithTabs(): ModuleDefinition[] {
  return MODULES.filter((m) => m.tabs.length > 0)
}

export function getModulesWithoutTabs(): ModuleDefinition[] {
  return MODULES.filter((m) => m.tabs.length === 0)
}

export function getAllModulesSorted(): ModuleDefinition[] {
  return [...getModulesWithTabs(), ...getModulesWithoutTabs()]
}
`
}

// ─────────────────────────────────────────────────────────────────────────────
// capabilities.ts

/**
 * Non-module capability codes（scope / 全域、不從 modules/ 衍生但保留）
 *
 * 規則：caller 用得到、但不屬於任何 module、codegen 保留現有 KEY
 */
const NON_MODULE_CAPABILITIES = new Set([
  'cross_branch.read',
  'cross_branch.write',
])

/**
 * 從現有 capabilities.ts 解析 value → KEY 對應、用於 codegen 保留現有 KEY 名稱
 * 譬如 'hr.roles.write' → 'HR_MANAGE_ROLES'（保留現有命名、避免 caller 全壞）
 */
function parseExistingCapabilityKeys(path: string): Map<string, string> {
  const map = new Map<string, string>()
  try {
    const src = readFileSync(path, 'utf8')
    const re = /^\s*([A-Z][A-Z0-9_]*):\s*'([a-z0-9_]+\.[a-z0-9_.\-]+)'/gm
    let m: RegExpExecArray | null
    while ((m = re.exec(src)) !== null) {
      map.set(m[2], m[1]) // value → KEY
    }
  } catch {
    // 第一次跑、檔不存在 / parse 失敗、回空 map
  }
  return map
}

/**
 * 自動命名 KEY：'tours.member.read' → 'TOURS_MEMBER_READ'
 */
function autoNameKey(code: string): string {
  return code.toUpperCase().replace(/[.\-]/g, '_')
}

function genCapabilitiesTs(): { out: string; stats: { derived: number; preserved: number; legacy: number } } {
  const capPath = join(REPO_ROOT, 'src/lib/permissions/capabilities.ts')
  const existingKeyMap = parseExistingCapabilityKeys(capPath)

  // 1. derived from modules/
  const derivedCodes = new Set<string>()
  for (const m of ALL_MODULES) {
    for (const code of deriveCapabilityCodes(m)) {
      derivedCodes.add(code)
    }
  }

  // 2. 結合 non-module exception
  const allCodes = new Set<string>([...derivedCodes, ...NON_MODULE_CAPABILITIES])

  // 3. legacy：現有 capabilities.ts 有、但 derived + non-module 都沒、保留（caller 還在用）
  //    例外：如果 'X.read' / 'X.write' 但 derived 已有 'X' (parent module-level)、
  //         視為「過時 sub-form」、不保留（避免 channels.manage.read/write 殘留）
  const legacyCodes: string[] = []
  for (const value of existingKeyMap.keys()) {
    if (allCodes.has(value)) continue
    const parts = value.split('.')
    if (parts.length >= 3) {
      const parent = parts.slice(0, -1).join('.')
      if (derivedCodes.has(parent)) continue // 父層已 derived、子層 deprecate
    }
    legacyCodes.push(value)
    allCodes.add(value)
  }

  // 4. 對每個 code 生 KEY（用現有優先、否則 auto-name）
  // 順序：先 module 衍生（依 module 順序）、再 non-module、再 legacy、KEY 內排序穩定
  const entries: { key: string; value: string; group: 'derived' | 'non-module' | 'legacy' }[] = []
  const seenKeys = new Set<string>()

  function addEntry(value: string, group: 'derived' | 'non-module' | 'legacy') {
    let key = existingKeyMap.get(value) ?? autoNameKey(value)
    // 防 KEY collision
    let suffix = 1
    while (seenKeys.has(key)) {
      key = `${autoNameKey(value)}_${suffix++}`
    }
    seenKeys.add(key)
    entries.push({ key, value, group })
  }

  // module 衍生（按 module 順序 → tab 順序）
  for (const m of ALL_MODULES) {
    for (const code of deriveCapabilityCodes(m)) {
      addEntry(code, 'derived')
    }
  }
  // non-module
  for (const code of NON_MODULE_CAPABILITIES) {
    addEntry(code, 'non-module')
  }
  // legacy
  for (const code of legacyCodes.sort()) {
    addEntry(code, 'legacy')
  }

  // 5. 產生 TS 輸出（分組註解）
  const lines: string[] = []
  let lastGroup: string | null = null
  let lastModulePrefix: string | null = null

  for (const e of entries) {
    if (e.group !== lastGroup) {
      lines.push('')
      if (e.group === 'derived') lines.push('  // ════ module 衍生（從 src/modules/* 自動產出）════')
      if (e.group === 'non-module') lines.push('  // ════ Non-module（scope / 全域 capability、不屬任何 module）════')
      if (e.group === 'legacy') lines.push('  // ════ Legacy（現有 caller 還在用、modules/ 沒衍生對應、之後審視）════')
      lastGroup = e.group
      lastModulePrefix = null
    }
    if (e.group === 'derived') {
      const prefix = e.value.split('.')[0]
      if (prefix !== lastModulePrefix) {
        lines.push(`  // ── ${prefix} ──`)
        lastModulePrefix = prefix
      }
    }
    lines.push(`  ${e.key}: '${e.value}',`)
  }

  const out = `${GENERATED_HEADER}

/**
 * Capability 常數（modules/ 衍生 + non-module exception + legacy）
 *
 * 跟 role_capabilities 表的 capability_code 欄位 1:1 對應。
 * caller 用：requireCapability(req, CAPABILITIES.HR_MANAGE_ROLES) 之類。
 */

export const CAPABILITIES = {
${lines.join('\n')}
} as const

export type Capability = (typeof CAPABILITIES)[keyof typeof CAPABILITIES]
`

  return {
    out,
    stats: {
      derived: derivedCodes.size,
      preserved: existingKeyMap.size,
      legacy: legacyCodes.length,
    },
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Runner

function main() {
  const featuresPath = join(REPO_ROOT, 'src/lib/permissions/features.ts')
  const moduleTabsPath = join(REPO_ROOT, 'src/lib/permissions/module-tabs.ts')
  const capabilitiesPath = join(REPO_ROOT, 'src/lib/permissions/capabilities.ts')

  const featuresOut = genFeaturesTs()
  const moduleTabsOut = genModuleTabsTs()
  const { out: capabilitiesOut, stats } = genCapabilitiesTs()

  writeFileSync(featuresPath, featuresOut, 'utf8')
  writeFileSync(moduleTabsPath, moduleTabsOut, 'utf8')
  writeFileSync(capabilitiesPath, capabilitiesOut, 'utf8')

  console.log(`✓ generated src/lib/permissions/features.ts (${ALL_MODULES.length} features)`)
  console.log(
    `✓ generated src/lib/permissions/module-tabs.ts (${getHrExposedModules().length} HR-exposed modules)`,
  )
  console.log(
    `✓ generated src/lib/permissions/capabilities.ts (${stats.derived} derived + ${NON_MODULE_CAPABILITIES.size} non-module + ${stats.legacy} legacy = ${stats.derived + NON_MODULE_CAPABILITIES.size + stats.legacy} total)`,
  )
  console.log('')
  console.log('下一步：跑 npm run type-check + npm run lint 確認')
  console.log('如果 type-check 失敗、可能是 caller 用了不再存在的 KEY、需要 caller migration')
}

main()
