#!/usr/bin/env node
/**
 * scripts/scaffold/new-route.mjs
 *
 * 新 API route scaffolder — 套 withAudit middleware、4 個 method placeholder。
 *
 * 用法：
 *   node scripts/scaffold/new-route.mjs <module>/<resource>             # dry-run
 *   node scripts/scaffold/new-route.mjs <module>/<resource> --apply     # 真的建檔
 *   npm run scaffold:route -- <module>/<resource>
 *   npm run scaffold:route -- <module>/<resource> --apply
 *
 * 例：
 *   node scripts/scaffold/new-route.mjs orders/comments
 *   → 產出 src/app/api/orders/comments/route.ts
 *
 * 規則：
 *   - module / resource 都必須是 kebab-case
 *   - 用 withAudit middleware（不寫 boilerplate）
 *   - GET / POST / PUT / DELETE 各有 placeholder（包 try-catch / capability / audit）
 *   - capability 自動推導：<module>.<resource>.<read|create|update|delete>
 *   - 預設 dry-run、不污染 repo
 *   - 不覆蓋既有檔案（檢查衝突直接 abort）
 *
 * 紅線：
 *   - 不動 capability seed（手動加）
 *   - 不動 RLS policy（手動加）
 *   - 不寫 E2E test（手動加）
 *   - 不 commit
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..', '..');
const API_DIR = path.join(PROJECT_ROOT, 'src', 'app', 'api');

// ---------- CLI ----------
const argv = process.argv.slice(2);
const apply = argv.includes('--apply');
const pathArg = argv.find((a) => !a.startsWith('--'));

if (!pathArg) {
  console.error('Usage: node scripts/scaffold/new-route.mjs <module>/<resource> [--apply]');
  console.error('  例: node scripts/scaffold/new-route.mjs orders/comments');
  process.exit(1);
}

const parts = pathArg.split('/').filter(Boolean);
if (parts.length !== 2) {
  console.error(`錯誤: 路徑格式必須是 <module>/<resource>、收到 "${pathArg}"`);
  console.error('  例: orders/comments、finance/invoices、tours/itineraries');
  process.exit(1);
}

const [moduleName, resource] = parts;

const KEBAB = /^[a-z][a-z0-9-]*$/;
if (!KEBAB.test(moduleName)) {
  console.error(`錯誤: module "${moduleName}" 必須是 kebab-case（小寫字母 + 連字號）`);
  process.exit(1);
}
if (!KEBAB.test(resource)) {
  console.error(`錯誤: resource "${resource}" 必須是 kebab-case（小寫字母 + 連字號）`);
  process.exit(1);
}

// ---------- 推導 ----------
const routeDir = path.join(API_DIR, moduleName, resource);
const routeFile = path.join(routeDir, 'route.ts');
const capabilityBase = `${moduleName}.${resource}`;

// ---------- Template ----------
const template = `/**
 * ${moduleName}/${resource} API route
 *
 * Auto-generated by scripts/scaffold/new-route.mjs
 *
 * 必走 pattern：
 *   - withAudit middleware（capability 守門 + audit context + Sentry）
 *   - ctx.supabase 是 admin client（per-request、不 singleton）
 *   - workspace 隔離靠 capability 守 + RLS 二次擋
 *   - mutation 必填 action / entityType（給 audit log + Sentry tag）
 *
 * 改完記得：
 *   1) 補 capability 進 hr/role_capabilities seed:
 *      - ${capabilityBase}.read
 *      - ${capabilityBase}.create
 *      - ${capabilityBase}.update
 *      - ${capabilityBase}.delete
 *   2) 補 RLS policy（用 has_capability_for_workspace）
 *   3) 補 E2E test（tests/e2e/ 下、跨 workspace 必失敗）
 *   4) 跑 npm run type-check && npm run lint
 */

import { NextResponse, type NextRequest } from 'next/server'
import { withAudit } from '@/lib/api/with-audit'

export const GET = withAudit(
  { capability: '${capabilityBase}.read' },
  async (req, ctx) => {
    // TODO: 實作查詢
    // const { data, error } = await ctx.supabase
    //   .from('${resource.replace(/-/g, '_')}')
    //   .select('id, ...')
    //   .eq('workspace_id', ctx.workspaceId)
    //   .is('deleted_at', null)
    // if (error) throw error
    // return NextResponse.json({ data })

    return NextResponse.json({ data: [] })
  }
)

export const POST = withAudit(
  {
    capability: '${capabilityBase}.create',
    action: 'create',
    entityType: '${resource}',
  },
  async (req, ctx) => {
    const body = await req.json()
    // TODO: 實作建立
    // const { data, error } = await ctx.supabase
    //   .from('${resource.replace(/-/g, '_')}')
    //   .insert({
    //     ...body,
    //     workspace_id: ctx.workspaceId,
    //     created_by: ctx.actorId,
    //   })
    //   .select()
    //   .single()
    // if (error) throw error
    // return NextResponse.json({ data })

    return NextResponse.json({ data: {} })
  }
)

export const PUT = withAudit(
  {
    capability: '${capabilityBase}.update',
    action: 'update',
    entityType: '${resource}',
  },
  async (req, ctx) => {
    const body = await req.json()
    // TODO: 實作更新
    // const { id, ...patch } = body
    // const { data, error } = await ctx.supabase
    //   .from('${resource.replace(/-/g, '_')}')
    //   .update({ ...patch, updated_by: ctx.actorId })
    //   .eq('id', id)
    //   .eq('workspace_id', ctx.workspaceId)
    //   .select()
    //   .single()
    // if (error) throw error
    // return NextResponse.json({ data })

    return NextResponse.json({ data: {} })
  }
)

export const DELETE = withAudit(
  {
    capability: '${capabilityBase}.delete',
    action: 'soft_delete',
    entityType: '${resource}',
  },
  async (req, ctx) => {
    const url = new URL(req.url)
    const id = url.searchParams.get('id')
    if (!id) {
      return NextResponse.json({ error: 'id 必填' }, { status: 400 })
    }
    // TODO: 實作軟刪除（不要直接 .delete()、走 softDelete helper 或 update deleted_at）
    // const { error } = await ctx.supabase
    //   .from('${resource.replace(/-/g, '_')}')
    //   .update({ deleted_at: new Date().toISOString(), updated_by: ctx.actorId })
    //   .eq('id', id)
    //   .eq('workspace_id', ctx.workspaceId)
    // if (error) throw error
    // return NextResponse.json({ ok: true })

    return NextResponse.json({ ok: true })
  }
)
`;

// ---------- Output ----------
const cyan = (s) => `\x1b[36m${s}\x1b[0m`;
const yellow = (s) => `\x1b[33m${s}\x1b[0m`;
const green = (s) => `\x1b[32m${s}\x1b[0m`;
const red = (s) => `\x1b[31m${s}\x1b[0m`;
const dim = (s) => `\x1b[2m${s}\x1b[0m`;

console.log('');
console.log(cyan('━━━ Venturo API route scaffolder ━━━'));
console.log(`  module    : ${green(moduleName)}`);
console.log(`  resource  : ${green(resource)}`);
console.log(`  file      : ${path.relative(PROJECT_ROOT, routeFile)}`);
console.log(`  capability: ${capabilityBase}.{read|create|update|delete}`);
console.log(`  mode      : ${apply ? red('--apply (write to disk)') : yellow('dry-run (no files written)')}`);
console.log('');

const exists = fs.existsSync(routeFile);
console.log(cyan('Plan:'));
if (exists) {
  console.log(`  ${red('✗')} ${path.relative(PROJECT_ROOT, routeFile)}  ${dim('(已存在、apply 會 abort)')}`);
} else {
  console.log(`  ${green('+')} ${path.relative(PROJECT_ROOT, routeFile)}  ${dim(`(${template.split('\n').length} 行、4 個 method)`)}`);
}
console.log('');

if (apply) {
  if (exists) {
    console.log(red(`Abort: ${path.relative(PROJECT_ROOT, routeFile)} 已存在、不覆蓋。`));
    process.exit(2);
  }
  fs.mkdirSync(routeDir, { recursive: true });
  fs.writeFileSync(routeFile, template, 'utf8');
  console.log(green(`✓ 已建 ${path.relative(PROJECT_ROOT, routeFile)}`));
} else {
  console.log(dim('（dry-run、沒寫檔。加 --apply 真的建檔。）'));
}

// ---------- Next steps ----------
console.log('');
console.log(cyan('下一步（手動處理、scaffolder 不碰）：'));
console.log('');
console.log(`  ${yellow('1.')} ${cyan('Capability seed')}（HR 顆粒度）：`);
console.log(`       ${dim('-')} 加進 hr/role_capabilities seed:`);
console.log(`           ${dim('•')} ${capabilityBase}.read`);
console.log(`           ${dim('•')} ${capabilityBase}.create`);
console.log(`           ${dim('•')} ${capabilityBase}.update`);
console.log(`           ${dim('•')} ${capabilityBase}.delete`);
console.log(`       ${dim('-')} 同步 src/lib/permissions/features.ts 推導邏輯`);
console.log('');
console.log(`  ${yellow('2.')} ${cyan('RLS policy')}（純加法 migration）：`);
console.log(`       ${dim('-')} CREATE POLICY 用 has_capability_for_workspace('${capabilityBase}.read', workspace_id)`);
console.log(`       ${dim('-')} 對應 4 個 capability 各一條 policy（read / insert / update / delete）`);
console.log(`       ${dim('-')} 寫進 supabase/migrations/<timestamp>_add_${moduleName}_${resource}_rls.sql`);
console.log(`       ${dim('-')} 注意：workspaces 表絕對不准 FORCE RLS（紅線 1）`);
console.log('');
console.log(`  ${yellow('3.')} ${cyan('E2E test')}：`);
console.log(`       ${dim('-')} tests/e2e/${moduleName}-${resource}.spec.ts`);
console.log(`       ${dim('-')} 至少含：跨 workspace 訪問必失敗、無 capability 必 403`);
console.log(`       ${dim('-')} 跑 npm run test:e2e -- ${moduleName}-${resource}`);
console.log('');
console.log(`  ${yellow('4.')} ${cyan('驗證')}：`);
console.log(`       ${dim('-')} npm run type-check`);
console.log(`       ${dim('-')} npm run lint`);
console.log(`       ${dim('-')} ./scripts/check-standards.sh --strict`);
console.log('');
