#!/usr/bin/env node
/**
 * scripts/scaffold/new-feature.mjs
 *
 * 新 feature scaffolder — 一次套完 Venturo ERP 的拆遷 pattern、不用記。
 *
 * 用法：
 *   node scripts/scaffold/new-feature.mjs <feature-name>             # dry-run（預設）
 *   node scripts/scaffold/new-feature.mjs <feature-name> --apply     # 真的建檔
 *   npm run scaffold:feature -- <feature-name>                       # 透過 npm script
 *   npm run scaffold:feature -- <feature-name> --apply
 *
 * 套的 pattern：
 *   - enforceWorkspaceScope（query / mutation 必走）
 *   - softDelete（不直接 .delete()）
 *   - withAudit（API mutation 必包）
 *   - .select('col1, col2')（不用 *）
 *   - createEntityHook（hook SSOT）
 *   - ListPageLayout + EnhancedTable（列表 UI）
 *
 * 紅線：
 *   - 預設 dry-run、不污染 repo
 *   - 不覆蓋既有檔案（apply 時會檢查、有同名直接 abort）
 *   - 不動到 sidebar / capability / RLS（手動處理、最後印「下一步」清單）
 */

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '..', '..');

// ---------- CLI ----------
const argv = process.argv.slice(2);
const apply = argv.includes('--apply');
const featureNameRaw = argv.find((a) => !a.startsWith('--'));

if (!featureNameRaw) {
  console.error('Usage: node scripts/scaffold/new-feature.mjs <feature-name> [--apply]');
  console.error('  feature-name 必須是 kebab-case（小寫 + 連字號）、例：orders、payment-requests');
  process.exit(1);
}

if (!/^[a-z][a-z0-9-]*$/.test(featureNameRaw)) {
  console.error(`錯誤：feature name "${featureNameRaw}" 格式不對。`);
  console.error('  必須是 kebab-case、開頭小寫字母、只能含小寫字母 / 數字 / 連字號。');
  process.exit(1);
}

// ---------- Naming helpers ----------
const kebab = featureNameRaw;                                          // payment-requests
const camel = kebab.replace(/-([a-z])/g, (_, c) => c.toUpperCase());   // paymentRequests
const Pascal = camel.charAt(0).toUpperCase() + camel.slice(1);         // PaymentRequests
const Singular = Pascal.endsWith('s') ? Pascal.slice(0, -1) : Pascal;  // PaymentRequest（給 type / hook 用）
const singularCamel = Singular.charAt(0).toLowerCase() + Singular.slice(1); // paymentRequest
const tableName = kebab.replace(/-/g, '_');                            // payment_requests

// ---------- Templates ----------
const HEADER = `/**
 * Auto-generated by scripts/scaffold/new-feature.mjs
 *
 * 必走 pattern：
 *   - enforceWorkspaceScope（查 + 改 + 刪）
 *   - softDelete 不直接 .delete()
 *   - withAudit middleware（API）
 *   - .select 明確列欄位、不用 *
 *
 * 改完記得：
 *   1) 補 capability 進 hr/role_capabilities seed
 *   2) 加 sidebar 入口 + ModuleGuard
 *   3) 加 RLS policy（用 has_capability_for_workspace）
 *   4) 跑 npm run type-check && npm run lint
 */
`;

const tplHook = () => `${HEADER}
import { createEntityHook } from '@/lib/hooks/create-entity-hook';
import { ${singularCamel}Service } from '../services/${kebab}.service';
import type { ${Singular} } from '../types';

/**
 * use${Pascal} — feature 層唯一對外 hook（SSOT）
 *
 * 不准在 component 直 import service / supabase client。
 */
export const use${Pascal} = createEntityHook<${Singular}>({
  key: '${kebab}',
  fetcher: ${singularCamel}Service.list,
  create: ${singularCamel}Service.create,
  update: ${singularCamel}Service.update,
  remove: ${singularCamel}Service.softRemove, // 走 softDelete、不要 .delete()
});
`;

const tplService = () => `${HEADER}
import { createBrowserClient } from '@/lib/supabase/browser';
import { enforceWorkspaceScope } from '@/lib/auth/enforce-workspace-scope';
import { softDelete } from '@/lib/data/soft-delete';
import type { ${Singular}, ${Singular}Insert, ${Singular}Update } from '../types';

const TABLE = '${tableName}';

// 明確 column list、不用 *
const COLUMNS = \`
  id,
  workspace_id,
  status,
  created_at,
  updated_at,
  deleted_at,
  created_by,
  updated_by
\`;

async function list(workspaceId: string): Promise<${Singular}[]> {
  const supabase = createBrowserClient();
  const query = supabase
    .from(TABLE)
    .select(COLUMNS)
    .is('deleted_at', null)
    .order('created_at', { ascending: false })
    .limit(20);

  const scoped = enforceWorkspaceScope(query, workspaceId);
  const { data, error } = await scoped;
  if (error) throw error;
  return (data ?? []) as ${Singular}[];
}

async function create(workspaceId: string, payload: ${Singular}Insert): Promise<${Singular}> {
  const supabase = createBrowserClient();
  const { data, error } = await supabase
    .from(TABLE)
    .insert({ ...payload, workspace_id: workspaceId })
    .select(COLUMNS)
    .single();
  if (error) throw error;
  return data as ${Singular};
}

async function update(workspaceId: string, id: string, patch: ${Singular}Update): Promise<${Singular}> {
  const supabase = createBrowserClient();
  const query = supabase
    .from(TABLE)
    .update(patch)
    .eq('id', id)
    .select(COLUMNS)
    .single();
  const scoped = enforceWorkspaceScope(query, workspaceId);
  const { data, error } = await scoped;
  if (error) throw error;
  return data as ${Singular};
}

// 不直接 .delete()、走 softDelete
async function softRemove(workspaceId: string, id: string, reason?: string) {
  return softDelete({ table: TABLE, id, workspaceId, reason });
}

export const ${singularCamel}Service = { list, create, update, softRemove };
`;

const tplListComponent = () => `${HEADER}
'use client';

import { ListPageLayout } from '@/components/layout/list-page-layout';
import { EnhancedTable } from '@/components/tables/enhanced-table';
import { use${Pascal} } from '../hooks/use${Pascal}';
import { ${kebab.toUpperCase().replace(/-/g, '_')}_LABELS, ${Singular.toUpperCase()}_STATUS } from '../constants';

export function ${Pascal}List() {
  const { data, loading, error } = use${Pascal}();

  return (
    <ListPageLayout
      title={${kebab.toUpperCase().replace(/-/g, '_')}_LABELS.pageTitle}
      loading={loading}
      error={error}
    >
      <EnhancedTable
        data={data ?? []}
        columns={[
          { key: 'id', label: ${kebab.toUpperCase().replace(/-/g, '_')}_LABELS.columns.id },
          { key: 'status', label: ${kebab.toUpperCase().replace(/-/g, '_')}_LABELS.columns.status },
          { key: 'created_at', label: ${kebab.toUpperCase().replace(/-/g, '_')}_LABELS.columns.createdAt },
        ]}
        // 列表分頁固定 15 筆、不給「每頁筆數」選擇器（SaaS 化讀取量 = 成本）
        pageSize={15}
      />
    </ListPageLayout>
  );
}
`;

const tplConstants = () => `${HEADER}
// Labels 集中管理、不要寫死在 component 裡

export const ${kebab.toUpperCase().replace(/-/g, '_')}_LABELS = {
  pageTitle: '${Pascal}',
  empty: '尚無資料',
  columns: {
    id: '編號',
    status: '狀態',
    createdAt: '建立時間',
  },
  actions: {
    create: '新增',
    edit: '編輯',
    delete: '刪除',
    save: '儲存',
    cancel: '取消',
  },
} as const;

// Status enum — 跟 DB schema 對齊
export const ${Singular.toUpperCase()}_STATUS = {
  DRAFT: 'draft',
  ACTIVE: 'active',
  ARCHIVED: 'archived',
} as const;

export type ${Singular}Status = (typeof ${Singular.toUpperCase()}_STATUS)[keyof typeof ${Singular.toUpperCase()}_STATUS];
`;

const tplTypes = () => `${HEADER}
// Feature-local types。如果 DB schema 有 generated types、改 import from '@/types/db'。

export interface ${Singular} {
  id: string;
  workspace_id: string;
  status: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
  created_by: string | null;
  updated_by: string | null;
}

export type ${Singular}Insert = Omit<${Singular}, 'id' | 'created_at' | 'updated_at' | 'deleted_at'>;
export type ${Singular}Update = Partial<Omit<${Singular}, 'id' | 'workspace_id' | 'created_at'>>;
`;

const tplIndex = () => `${HEADER}
export * from './hooks/use${Pascal}';
export * from './components/${Pascal}List';
export * from './constants';
export type { ${Singular}, ${Singular}Insert, ${Singular}Update } from './types';
`;

const tplHookTest = () => `${HEADER}
import { describe, it, expect, vi } from 'vitest';
import { renderHook, waitFor } from '@testing-library/react';
import { use${Pascal} } from '@/features/${kebab}/hooks/use${Pascal}';

vi.mock('@/features/${kebab}/services/${kebab}.service', () => ({
  ${singularCamel}Service: {
    list: vi.fn().mockResolvedValue([]),
    create: vi.fn(),
    update: vi.fn(),
    softRemove: vi.fn(),
  },
}));

describe('use${Pascal}', () => {
  it('initially loading then resolves to empty list', async () => {
    const { result } = renderHook(() => use${Pascal}());
    await waitFor(() => expect(result.current.loading).toBe(false));
    expect(result.current.data).toEqual([]);
    expect(result.current.error).toBeNull();
  });
});
`;

const tplServiceTest = () => `${HEADER}
import { describe, it, expect } from 'vitest';
import { ${singularCamel}Service } from '@/features/${kebab}/services/${kebab}.service';

describe('${singularCamel}Service', () => {
  it('exports the expected surface', () => {
    expect(typeof ${singularCamel}Service.list).toBe('function');
    expect(typeof ${singularCamel}Service.create).toBe('function');
    expect(typeof ${singularCamel}Service.update).toBe('function');
    expect(typeof ${singularCamel}Service.softRemove).toBe('function');
  });

  // TODO: workspace scope 測試、softDelete 測試、補 mock supabase client
});
`;

// ---------- Plan ----------
const featureDir = path.join(PROJECT_ROOT, 'src', 'features', kebab);
const testDir = path.join(PROJECT_ROOT, 'tests', 'features', kebab);

const files = [
  { path: path.join(featureDir, 'hooks', `use${Pascal}.ts`), content: tplHook() },
  { path: path.join(featureDir, 'services', `${kebab}.service.ts`), content: tplService() },
  { path: path.join(featureDir, 'components', `${Pascal}List.tsx`), content: tplListComponent() },
  { path: path.join(featureDir, 'constants', 'index.ts'), content: tplConstants() },
  { path: path.join(featureDir, 'types', 'index.ts'), content: tplTypes() },
  { path: path.join(featureDir, 'index.ts'), content: tplIndex() },
  { path: path.join(testDir, 'hooks', `use${Pascal}.test.ts`), content: tplHookTest() },
  { path: path.join(testDir, 'services', `${kebab}.service.test.ts`), content: tplServiceTest() },
];

// ---------- Output ----------
const cyan = (s) => `\x1b[36m${s}\x1b[0m`;
const yellow = (s) => `\x1b[33m${s}\x1b[0m`;
const green = (s) => `\x1b[32m${s}\x1b[0m`;
const red = (s) => `\x1b[31m${s}\x1b[0m`;
const dim = (s) => `\x1b[2m${s}\x1b[0m`;

console.log('');
console.log(cyan('━━━ Venturo feature scaffolder ━━━'));
console.log(`  feature   : ${green(kebab)}`);
console.log(`  Pascal    : ${Pascal}    (Singular: ${Singular})`);
console.log(`  table     : ${tableName}`);
console.log(`  mode      : ${apply ? red('--apply (write to disk)') : yellow('dry-run (no files written)')}`);
console.log('');
console.log(cyan('Plan — 將建立的檔案：'));

let conflict = false;
for (const f of files) {
  const rel = path.relative(PROJECT_ROOT, f.path);
  const exists = fs.existsSync(f.path);
  if (exists) {
    console.log(`  ${red('✗')} ${rel}  ${dim('(已存在、apply 會 abort)')}`);
    conflict = true;
  } else {
    console.log(`  ${green('+')} ${rel}  ${dim(`(${f.content.split('\n').length} 行)`)}`);
  }
}

console.log('');

if (apply) {
  if (conflict) {
    console.log(red('Abort: 有檔案已存在、不覆蓋。請手動處理或換 feature name。'));
    process.exit(2);
  }
  console.log(cyan('Writing files...'));
  for (const f of files) {
    fs.mkdirSync(path.dirname(f.path), { recursive: true });
    fs.writeFileSync(f.path, f.content, 'utf8');
    console.log(`  ${green('✓')} ${path.relative(PROJECT_ROOT, f.path)}`);
  }
  console.log('');
  console.log(green('✓ Scaffold 完成。'));
} else {
  console.log(dim('（dry-run、沒寫檔。加 --apply 真的建檔。）'));
}

// ---------- Next steps ----------
console.log('');
console.log(cyan('下一步（手動處理、scaffolder 不碰）：'));
console.log('');
console.log(`  ${yellow('1.')} ${cyan('Capability')}（HR 顆粒度、三段式 code）：`);
console.log(`     在 hr/role_capabilities seed 加：`);
console.log(`       ${dim('-')} ${kebab}.list.read`);
console.log(`       ${dim('-')} ${kebab}.list.write`);
console.log(`       ${dim('-')} ${kebab}.list.delete`);
console.log(`     並更新 src/lib/permissions/features.ts 推導邏輯`);
console.log('');
console.log(`  ${yellow('2.')} ${cyan('Sidebar / 路由')}：`);
console.log(`       ${dim('-')} 加 src/app/(app)/${kebab}/page.tsx 用 ModuleGuard 包 ${Pascal}List`);
console.log(`       ${dim('-')} 加 sidebar 入口（SidebarNav config 對應位置）`);
console.log(`       ${dim('-')} 加 breadcrumb`);
console.log('');
console.log(`  ${yellow('3.')} ${cyan('DB schema + RLS')}（純加法 migration、可直接 apply）：`);
console.log(`       ${dim('-')} CREATE TABLE public.${tableName}（含 workspace_id / deleted_at / 審計欄位 FK → employees(id)）`);
console.log(`       ${dim('-')} ENABLE ROW LEVEL SECURITY（記得 NO FORCE）`);
console.log(`       ${dim('-')} CREATE POLICY 用 has_capability_for_workspace('${kebab}.list.read', workspace_id)`);
console.log(`       ${dim('-')} 寫進 supabase/migrations/<timestamp>_create_${tableName}.sql`);
console.log('');
console.log(`  ${yellow('4.')} ${cyan('API route')}（如果需要 server-side mutation）：`);
console.log(`       ${dim('-')} src/app/api/${kebab}/route.ts 用 require-capability + withAudit`);
console.log('');
console.log(`  ${yellow('5.')} ${cyan('驗證')}：`);
console.log(`       ${dim('-')} npm run type-check`);
console.log(`       ${dim('-')} npm run lint`);
console.log(`       ${dim('-')} npm run test -- ${kebab}`);
console.log(`       ${dim('-')} ./scripts/check-standards.sh --strict`);
console.log('');
