export const DEMO_MODE =
  process.env.NEXT_PUBLIC_DEMO_MODE === 'true' ||
  (!process.env.NEXT_PUBLIC_SUPABASE_URL && !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY)

export const demoCapabilities = [
  'dashboard.read',
  'settings.read',
  'workspaces.read',
  'tours.read',
  'orders.read',
  'finance.read',
  'accounting.read',
  'calendar.read',
  'todos.read',
  'channels.read',
  'office.read',
  'hr.read',
  'database.read',
  'ai_hub.read',
  'documents.read',
  'customers.read',
  'shared_data_management.read',
  'platform_integrations.read',
  'visas.read',
  'esim.read',
  'travel_invoice.read',
]

export const demoFeatures = [
  'dashboard',
  'settings',
  'workspaces',
  'tours',
  'orders',
  'finance',
  'accounting',
  'calendar',
  'todos',
  'channels',
  'office',
  'hr',
  'database',
  'ai_hub',
  'documents',
  'customers',
  'shared_data_management',
  'platform_integrations',
  'visas',
  'esim',
  'travel_invoice',
]

export const demoLayoutContextPayload = {
  ok: true,
  user: { id: 'demo-user', email: 'demo@local' },
  employee: {
    id: 'demo-employee',
    employee_number: 'DEMO',
    display_name: 'Demo 使用者',
    english_name: 'Demo User',
    role_id: 'demo-role',
    workspace_id: 'demo-workspace',
    status: 'active',
    branch_id: null,
  },
  workspace: {
    id: 'demo-workspace',
    code: 'DEMO',
    name: 'Demo Workspace',
    type: null,
    is_active: true,
    premium_enabled: true,
    default_billing_day_of_week: 4,
  },
  role_id: 'demo-role',
  workspace_id: 'demo-workspace',
  capabilities: demoCapabilities,
  features: demoFeatures,
  premium_enabled: true,
} as const

