-- 建立權限相關資料表和輔助函數
-- 執行時間: 身份遷移和 creator_user_id 回填完成後

-- 1. 建立 Itinerary_Permissions 表 (需先建立，因為函數會引用它)
-- 注意: itineraries.id 實際上是 text 類型（雖然內容是 UUID 格式）
CREATE TABLE IF NOT EXISTS "Itinerary_Permissions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "itinerary_id" text NOT NULL REFERENCES "itineraries"(id) ON DELETE CASCADE,
  "user_id" uuid NOT NULL REFERENCES "auth"."users"(id) ON DELETE CASCADE,
  "permission_level" text NOT NULL,
  "created_at" timestamptz DEFAULT now(),
  UNIQUE(itinerary_id, user_id)
);

-- 2. 建立 Tour_Expenses 表
CREATE TABLE IF NOT EXISTS "Tour_Expenses" (
  "expense_id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "itinerary_id" text NOT NULL REFERENCES "itineraries"(id) ON DELETE CASCADE,
  "leader_id" uuid NOT NULL REFERENCES "auth"."users"(id) ON DELETE CASCADE,
  "actual_amount" numeric NOT NULL,
  "notes" text,
  "created_at" timestamptz DEFAULT now()
);

-- 3. 建立權限檢查輔助函數 (在表格建立後)
-- 注意: itinerary_id 改為 text 類型
CREATE OR REPLACE FUNCTION get_user_permission(p_user_id uuid, p_itinerary_id text)
RETURNS text AS $$
  SELECT permission_level FROM "Itinerary_Permissions"
  WHERE "Itinerary_Permissions".user_id = p_user_id
    AND "Itinerary_Permissions".itinerary_id = p_itinerary_id;
$$ LANGUAGE sql STABLE;

-- 4. 建立索引
CREATE INDEX IF NOT EXISTS idx_itinerary_permissions_user ON "Itinerary_Permissions"(user_id);
CREATE INDEX IF NOT EXISTS idx_itinerary_permissions_itinerary ON "Itinerary_Permissions"(itinerary_id);
CREATE INDEX IF NOT EXISTS idx_tour_expenses_itinerary ON "Tour_Expenses"(itinerary_id);
CREATE INDEX IF NOT EXISTS idx_tour_expenses_leader ON "Tour_Expenses"(leader_id);
