-- ─────────────────────────────────────────────────────────────────────────────
-- Seed ref_countries from legacy venturo-erp（漫途用過的 86 筆國家）
-- 來源：舊 venturo-erp Supabase（ref=wzvwmawpkapcmkfmkvav）/ public.ref_countries
-- 範圍：86 筆（亞洲 / 歐洲 / 美洲 / 非洲 / 大洋洲）、漫途旅遊業務累積
-- 註：舊表帶 workspace_id（NOT NULL with default = 漫途舊 workspace）、本 migration 砍掉、改全平台共用
-- ─────────────────────────────────────────────────────────────────────────────

BEGIN;

INSERT INTO public.ref_countries (code, name_zh, name_en, continent, sub_region, is_active) VALUES
  ('AE', '阿聯', 'United Arab Emirates', 'Asia', '中東', true),
  ('AL', '阿爾巴尼亞', 'Albania', 'Europe', '南歐', true),
  ('AR', '阿根廷', 'Argentina', 'South America', '南美', true),
  ('AT', '奧地利', 'Austria', 'Europe', '中東歐', true),
  ('AU', '澳洲', 'Australia', 'Oceania', '大洋洲', true),
  ('BA', '波士尼亞', 'Bosnia and Herzegovina', 'Europe', '中東歐', true),
  ('BE', '比利時', 'Belgium', 'Europe', '西歐', true),
  ('BG', '保加利亞', 'Bulgaria', 'Europe', '中東歐', true),
  ('BN', '汶萊', 'Brunei', 'Asia', '東南亞', true),
  ('BO', '玻利維亞', 'Bolivia', 'South America', '南美', true),
  ('BR', '巴西', 'Brazil', 'South America', '南美', true),
  ('CA', '加拿大', 'Canada', 'North America', '北美', true),
  ('CH', '瑞士', 'Switzerland', 'Europe', '西歐', true),
  ('CL', '智利', 'Chile', 'South America', '南美', true),
  ('CN', '中國', 'China', 'Asia', '中國', true),
  ('CO', '哥倫比亞', 'Colombia', 'South America', '南美', true),
  ('CU', '古巴', 'Cuba', 'North America', '北美', true),
  ('CZ', '捷克', 'Czech Republic', 'Europe', '中東歐', true),
  ('DE', '德國', 'Germany', 'Europe', '西歐', true),
  ('DK', '丹麥', 'Denmark', 'Europe', '北歐', true),
  ('EE', '愛沙尼亞', 'Estonia', 'Europe', '北歐', true),
  ('EG', '埃及', 'Egypt', 'Africa', '非洲', true),
  ('ES', '西班牙', 'Spain', 'Europe', '南歐', true),
  ('FI', '芬蘭', 'Finland', 'Europe', '北歐', true),
  ('FJ', '斐濟', 'Fiji', 'Oceania', '大洋洲', true),
  ('FR', '法國', 'France', 'Europe', '西歐', true),
  ('GB', '英國', 'United Kingdom', 'Europe', '西歐', true),
  ('GE', '喬治亞', 'Georgia', 'Asia', '中東', true),
  ('GR', '希臘', 'Greece', 'Europe', '南歐', true),
  ('HK', '香港', 'Hong Kong', 'Asia', '中國', true),
  ('HR', '克羅埃西亞', 'Croatia', 'Europe', '南歐', true),
  ('HU', '匈牙利', 'Hungary', 'Europe', '中東歐', true),
  ('ID', '印尼', 'Indonesia', 'Asia', '東南亞', true),
  ('IE', '愛爾蘭', 'Ireland', 'Europe', '西歐', true),
  ('IL', '以色列', 'Israel', 'Asia', '中東', true),
  ('IN', '印度', 'India', 'Asia', '南亞', true),
  ('IS', '冰島', 'Iceland', 'Europe', '北歐', true),
  ('IT', '義大利', 'Italy', 'Europe', '南歐', true),
  ('JO', '約旦', 'Jordan', 'Asia', '中東', true),
  ('JP', '日本', 'Japan', 'Asia', '東北亞', true),
  ('KE', '肯亞', 'Kenya', 'Africa', '非洲', true),
  ('KH', '柬埔寨', 'Cambodia', 'Asia', '東南亞', true),
  ('KR', '韓國', 'South Korea', 'Asia', '東北亞', true),
  ('KZ', '哈薩克', 'Kazakhstan', 'Asia', '中亞', true),
  ('LA', '寮國', 'Laos', 'Asia', '東南亞', true),
  ('LK', '斯里蘭卡', 'Sri Lanka', 'Asia', '南亞', true),
  ('LT', '立陶宛', 'Lithuania', 'Europe', '北歐', true),
  ('LU', '盧森堡', 'Luxembourg', 'Europe', '西歐', true),
  ('LV', '拉脫維亞', 'Latvia', 'Europe', '北歐', true),
  ('MA', '摩洛哥', 'Morocco', 'Africa', '非洲', true),
  ('ME', '蒙特內哥羅', 'Montenegro', 'Europe', '南歐', true),
  ('MK', '北馬其頓', 'North Macedonia', 'Europe', '南歐', true),
  ('MM', '緬甸', 'Myanmar', 'Asia', '東南亞', true),
  ('MN', '蒙古', 'Mongolia', 'Asia', '東北亞', true),
  ('MO', '澳門', 'Macau', 'Asia', '中國', true),
  ('MV', '馬爾地夫', 'Maldives', 'Asia', '南亞', true),
  ('MX', '墨西哥', 'Mexico', 'North America', '北美', true),
  ('MY', '馬來西亞', 'Malaysia', 'Asia', '東南亞', true),
  ('NL', '荷蘭', 'Netherlands', 'Europe', '西歐', true),
  ('NO', '挪威', 'Norway', 'Europe', '北歐', true),
  ('NP', '尼泊爾', 'Nepal', 'Asia', '南亞', true),
  ('NZ', '紐西蘭', 'New Zealand', 'Oceania', '大洋洲', true),
  ('OM', '阿曼', 'Oman', 'Asia', '中東', true),
  ('PE', '秘魯', 'Peru', 'South America', '南美', true),
  ('PH', '菲律賓', 'Philippines', 'Asia', '東南亞', true),
  ('PL', '波蘭', 'Poland', 'Europe', '中東歐', true),
  ('PT', '葡萄牙', 'Portugal', 'Europe', '南歐', true),
  ('PW', '帛琉', 'Palau', 'Oceania', '大洋洲', true),
  ('QA', '卡達', 'Qatar', 'Asia', '中東', true),
  ('RO', '羅馬尼亞', 'Romania', 'Europe', '中東歐', true),
  ('RS', '塞爾維亞', 'Serbia', 'Europe', '中東歐', true),
  ('RU', '俄羅斯', 'Russia', 'Europe', '中東歐', true),
  ('SA', '沙烏地阿拉伯', 'Saudi Arabia', 'Asia', '中東', true),
  ('SE', '瑞典', 'Sweden', 'Europe', '北歐', true),
  ('SG', '新加坡', 'Singapore', 'Asia', '東南亞', true),
  ('SI', '斯洛維尼亞', 'Slovenia', 'Europe', '南歐', true),
  ('SK', '斯洛伐克', 'Slovakia', 'Europe', '中東歐', true),
  ('TH', '泰國', 'Thailand', 'Asia', '東南亞', true),
  ('TN', '突尼西亞', 'Tunisia', 'Africa', '非洲', true),
  ('TR', '土耳其', 'Turkey', 'Asia', '中東', true),
  ('TW', '台灣', 'Taiwan', 'Asia', '東北亞', true),
  ('TZ', '坦尚尼亞', 'Tanzania', 'Africa', '非洲', true),
  ('US', '美國', 'United States', 'North America', '北美', true),
  ('UZ', '烏茲別克', 'Uzbekistan', 'Asia', '中亞', true),
  ('VN', '越南', 'Vietnam', 'Asia', '東南亞', true),
  ('ZA', '南非', 'South Africa', 'Africa', '非洲', true)
ON CONFLICT (code) DO UPDATE SET
  name_zh = EXCLUDED.name_zh,
  name_en = EXCLUDED.name_en,
  continent = EXCLUDED.continent,
  sub_region = EXCLUDED.sub_region;

NOTIFY pgrst, 'reload schema';

COMMIT;
