-- =====================================================
-- Venturo ERP - 完整修復 itinerary_permissions 問題
-- 檔案：20260113100000_fix_itinerary_permissions_complete.sql
-- 日期：2026-01-13
--
-- 問題：
-- 1. RLS 策略引用了不存在的 Itinerary_Permissions 表格
-- 2. get_user_permission 函數有依賴需要先清理
--
-- 解決方案：
-- 1. 先刪除所有依賴 get_user_permission 的策略
-- 2. 確保 itinerary_permissions 表格存在
-- 3. 重新創建 get_user_permission 函數
-- 4. 創建新的 RLS 策略（基於 workspace_id）
-- =====================================================

BEGIN;

-- ============================================
-- 1. 先刪除所有依賴的 RLS 策略
-- ============================================

-- itineraries 表的策略
DROP POLICY IF EXISTS "Users can view itineraries they are a part of" ON public.itineraries;
DROP POLICY IF EXISTS "Editors can update their itineraries" ON public.itineraries;
DROP POLICY IF EXISTS "Editors can delete itineraries" ON public.itineraries;
DROP POLICY IF EXISTS "itineraries_select" ON public.itineraries;
DROP POLICY IF EXISTS "itineraries_insert" ON public.itineraries;
DROP POLICY IF EXISTS "itineraries_update" ON public.itineraries;
DROP POLICY IF EXISTS "itineraries_delete" ON public.itineraries;

-- tour_expenses 表的策略（如果存在）
DROP POLICY IF EXISTS "Editors can manage expenses for their itineraries" ON public.tour_expenses;
DROP POLICY IF EXISTS "tour_expenses_select" ON public.tour_expenses;
DROP POLICY IF EXISTS "tour_expenses_all" ON public.tour_expenses;

-- itinerary_permissions 表的策略
DROP POLICY IF EXISTS "Users can see their own permissions" ON public.itinerary_permissions;
DROP POLICY IF EXISTS "Editors can manage permissions for their itineraries" ON public.itinerary_permissions;
DROP POLICY IF EXISTS "itinerary_permissions_select" ON public.itinerary_permissions;
DROP POLICY IF EXISTS "itinerary_permissions_all" ON public.itinerary_permissions;

-- ============================================
-- 2. 刪除舊函數（現在沒有依賴了）
-- ============================================

DROP FUNCTION IF EXISTS get_user_permission(uuid, uuid) CASCADE;
DROP FUNCTION IF EXISTS get_user_permission(uuid, text) CASCADE;

-- ============================================
-- 3. 確保 itinerary_permissions 表格存在
-- ============================================

-- 先刪除可能存在的舊表格（使用舊名稱）
DROP TABLE IF EXISTS public."Itinerary_Permissions" CASCADE;
DROP TABLE IF EXISTS public."Tour_Expenses" CASCADE;

-- 創建 itinerary_permissions 表格
CREATE TABLE IF NOT EXISTS public.itinerary_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itinerary_id TEXT NOT NULL,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  permission_level TEXT NOT NULL DEFAULT 'viewer',
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(itinerary_id, user_id)
);

-- 創建 tour_expenses 表格
CREATE TABLE IF NOT EXISTS public.tour_expenses (
  expense_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  itinerary_id TEXT NOT NULL,
  leader_id UUID NOT NULL,
  actual_amount NUMERIC NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 創建索引
CREATE INDEX IF NOT EXISTS idx_itinerary_permissions_user ON public.itinerary_permissions(user_id);
CREATE INDEX IF NOT EXISTS idx_itinerary_permissions_itinerary ON public.itinerary_permissions(itinerary_id);
CREATE INDEX IF NOT EXISTS idx_tour_expenses_itinerary ON public.tour_expenses(itinerary_id);
CREATE INDEX IF NOT EXISTS idx_tour_expenses_leader ON public.tour_expenses(leader_id);

-- ============================================
-- 4. 創建 get_user_permission 函數
-- ============================================

CREATE OR REPLACE FUNCTION get_user_permission(p_user_id UUID, p_itinerary_id TEXT)
RETURNS TEXT AS $$
BEGIN
  RETURN (
    SELECT permission_level FROM public.itinerary_permissions
    WHERE itinerary_permissions.user_id = p_user_id
      AND itinerary_permissions.itinerary_id = p_itinerary_id
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- ============================================
-- 5. 創建新的 itineraries RLS 策略
-- ============================================

ALTER TABLE public.itineraries ENABLE ROW LEVEL SECURITY;

-- SELECT: 同 workspace 或 super_admin 可以讀取
DROP POLICY IF EXISTS "itineraries_select" ON public.itineraries;
CREATE POLICY "itineraries_select" ON public.itineraries FOR SELECT
USING (
  workspace_id = get_current_user_workspace()
  OR workspace_id IS NULL
  OR is_super_admin()
);

-- INSERT: 同 workspace 可以新增
DROP POLICY IF EXISTS "itineraries_insert" ON public.itineraries;
CREATE POLICY "itineraries_insert" ON public.itineraries FOR INSERT
WITH CHECK (
  workspace_id = get_current_user_workspace()
  OR workspace_id IS NULL
);

-- UPDATE: 同 workspace 或 super_admin 可以更新
DROP POLICY IF EXISTS "itineraries_update" ON public.itineraries;
CREATE POLICY "itineraries_update" ON public.itineraries FOR UPDATE
USING (
  workspace_id = get_current_user_workspace()
  OR workspace_id IS NULL
  OR is_super_admin()
);

-- DELETE: 同 workspace 或 super_admin 可以刪除
DROP POLICY IF EXISTS "itineraries_delete" ON public.itineraries;
CREATE POLICY "itineraries_delete" ON public.itineraries FOR DELETE
USING (
  workspace_id = get_current_user_workspace()
  OR workspace_id IS NULL
  OR is_super_admin()
);

-- ============================================
-- 6. 創建 itinerary_permissions RLS 策略
-- ============================================

ALTER TABLE public.itinerary_permissions ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "itinerary_permissions_select" ON public.itinerary_permissions;
CREATE POLICY "itinerary_permissions_select" ON public.itinerary_permissions FOR SELECT
USING (
  auth.uid() = user_id
  OR is_super_admin()
);

DROP POLICY IF EXISTS "itinerary_permissions_all" ON public.itinerary_permissions;
CREATE POLICY "itinerary_permissions_all" ON public.itinerary_permissions FOR ALL
USING (is_super_admin())
WITH CHECK (is_super_admin());

-- ============================================
-- 7. 創建 tour_expenses RLS 策略
-- ============================================

ALTER TABLE public.tour_expenses ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tour_expenses_select" ON public.tour_expenses;
CREATE POLICY "tour_expenses_select" ON public.tour_expenses FOR SELECT
USING (
  auth.uid() = leader_id
  OR is_super_admin()
);

DROP POLICY IF EXISTS "tour_expenses_all" ON public.tour_expenses;
CREATE POLICY "tour_expenses_all" ON public.tour_expenses FOR ALL
USING (is_super_admin())
WITH CHECK (is_super_admin());

COMMIT;
